In [14]:
import pandas as pd

In [19]:
saida = pd.read_csv('saida_2.csv', sep=';',encoding='latin-1',usecols=[13])
saida

ParserError: Error tokenizing data. C error: EOF inside string starting at row 91205

In [21]:
pd.read_csv("altered_saida.csv")

,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column12,Column13,Column14
0,18/02/2020 20:45,20DCNIT18/02/2020 20:45,0,0,0,0,5.4,215.0,-22.863960,-43.099190,Barreto 1
1,18/02/2020 20:45,21DCNIT18/02/2020 20:45,0,0,0,0,2.2,203.2,-22.885602,-43.104860,Boa Vista
2,18/02/2020 20:45,22DCNIT18/02/2020 20:45,0,0,0,0,0.4,165.0,-22.882610,-43.065750,Caramujo
3,18/02/2020 20:45,36DCNIT18/02/2020 20:45,0,0,0,0,0.0,196.4,-22.912318,-43.102392,Cavalão
4,18/02/2020 20:45,18DCNIT18/02/2020 20:45,0,0,0,0,0.0,157.0,-22.934441,-43.006239,Engenho do Mato
...,...,...,...,...,...,...,...,...,...,...,...
1048570,08/03/2021 13:30,30DCNIT08/03/2021 13:30,0,0,0,0,23.2,23.2,-22.934162,-43.100285,Preventório
1048571,08/03/2021 13:30,31DCNIT08/03/2021 13:30,0,0,0,0,42.0,42.0,-22.876405,-43.046370,Santa Bárbara 2
1048572,08/03/2021 13:30,24DCNIT08/03/2021 13:30,0,0,0,0,40.2,40.2,-22.902903,-43.086738,Travessa Beltrão
1048573,08/03/2021 13:45,18DCNIT08/03/2021 13:45,0,0,0,0,27.0,27.0,-22.934441,-43.006239,Engenho do Mato
1048574,08/03/2021 13:45,20DCNIT08/03/2021 13:45,0,0,0,0,50.8,50.8,-22.863960,-43.099190,Barreto 1